server:
  port: 8080
  hostname: 0.0.0.0
  read_timeout: 15
  write_timeout: 15
database:
  host: 194.87.234.96
  port: 5432 
  username: eebo
  password: "eebo"
  database_name: eebo
clusters:
  hostname: 0.0.0.0
  port: 80