server:
  port: 8080
  hostname: localhost
  read_timeout: 15
  write_timeout: 15
database:
  host: 172.21.208.1
  port: 5432 
  username: eebo
  password: "E]j4<oZPUimz8–&"
  database_name: eebo_team
